name: 'Prime caches'
author: 'EnricoMi'
description: 'A GitHub Action that primes caches'

inputs:
  spark-version:
    description: Spark version, e.g. 3.4.0 or 3.4.0-SNAPSHOT
    required: true
  scala-version:
    description: Scala version, e.g. 2.12.15
    required: true
  spark-compat-version:
    description: Spark compatibility version, e.g. 3.4
    required: true
  scala-compat-version:
    description: Scala compatibility version, e.g. 2.12
    required: true
  java-compat-version:
    description: Java compatibility version, e.g. 8
    required: true
  hadoop-version:
    description: Hadoop version, e.g. 2.7 or 2
    required: true

runs:
  using: 'composite'
  steps:
  - name: Set versions in pom.xml
    run: |
      ./set-version.sh ${{ inputs.spark-version }} ${{ inputs.scala-version }}
      git diff
    shell: bash

  - name: Check Maven packages cache
    id: mvn-build-cache
    uses: actions/cache@v4
    with:
      lookup-only: true
      path: ~/.m2/repository
      key: ${{ runner.os }}-mvn-build-${{ inputs.spark-version }}-${{ inputs.scala-version }}-${{ hashFiles('pom.xml') }}

  - name: Check Spark Binaries cache
    id: spark-binaries-cache
    uses: actions/cache@v4
    with:
      lookup-only: true
      path: ~/spark
      key: ${{ runner.os }}-spark-binaries-${{ inputs.spark-version }}-${{ inputs.scala-compat-version }}

  - name: Prepare priming caches
    id: setup
    run: |
      # Prepare priming caches
      if [ -z "${{ steps.mvn-build-cache.outputs.cache-hit }}" ]; then
        echo "prime-mvn-cache=true" >> "$GITHUB_ENV"
        echo "prime-some-cache=true" >> "$GITHUB_ENV"
      fi;
      if [ -z "${{ steps.spark-binaries-cache.outputs.cache-hit }}" ]; then
        echo "prime-spark-cache=true" >> "$GITHUB_ENV"
        echo "prime-some-cache=true" >> "$GITHUB_ENV"
      fi;
    shell: bash

  - name: Setup JDK ${{ inputs.java-compat-version }}
    if: env.prime-some-cache
    uses: actions/setup-java@v4
    with:
      java-version: ${{ inputs.java-compat-version }}
      distribution: 'zulu'

  - name: Build
    if: env.prime-mvn-cache
    env:
      JDK_JAVA_OPTIONS: --add-exports java.base/sun.nio.ch=ALL-UNNAMED --add-exports java.base/sun.util.calendar=ALL-UNNAMED
    run: |
      # Build
      echo "::group::mvn dependency:go-offline"
      mvn --batch-mode dependency:go-offline
      echo "::endgroup::"
    shell: bash

  - name: Save Maven packages cache
    if: env.prime-mvn-cache
    uses: actions/cache/save@v4
    with:
      path: ~/.m2/repository
      key: ${{ runner.os }}-mvn-build-${{ inputs.spark-version }}-${{ inputs.scala-version }}-${{ hashFiles('pom.xml') }}-${{ github.run_id }}

  - name: Setup Spark Binaries
    if: env.prime-spark-cache && ! contains(inputs.spark-version, '-SNAPSHOT')
    env:
      SPARK_PACKAGE: spark-${{ inputs.spark-version }}/spark-${{ inputs.spark-version }}-bin-hadoop${{ inputs.hadoop-version }}${{ startsWith(inputs.spark-version, '3.') && inputs.scala-compat-version == '2.13' && '-scala2.13' || '' }}.tgz
    run: |
      wget --progress=dot:giga "https://www.apache.org/dyn/closer.lua/spark/${SPARK_PACKAGE}?action=download" -O - | tar -xzC "${{ runner.temp }}"
      archive=$(basename "${SPARK_PACKAGE}") bash -c "mv -v "${{ runner.temp }}/\${archive/%.tgz/}" ~/spark"
    shell: bash

  - name: Save Spark Binaries cache
    if: env.prime-spark-cache && ! contains(inputs.spark-version, '-SNAPSHOT')
    uses: actions/cache/save@v4
    with:
      path: ~/spark
      key: ${{ runner.os }}-spark-binaries-${{ inputs.spark-version }}-${{ inputs.scala-compat-version }}-${{ github.run_id }}

branding:
  icon: 'check-circle'
  color: 'green'
