version: "3"
services:
  master:
    container_name: spark-master
    image: spark-extension-example-docker
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master -h master
    environment:
      MASTER: spark://master:7077
      SPARK_PUBLIC_DNS: localhost
      SPARK_MASTER_WEBUI_PORT: 8080
      PYSPARK_PYTHON: python${PYTHON_VERSION:-3.8}
      PYSPARK_DRIVER_PYTHON: python${PYTHON_VERSION:-3.8}
    expose:
      - 7077
    ports:
      - 4040:4040
      - 8080:8080
    volumes:
      - ./:/example

  worker:
    container_name: spark-worker
    image: spark-extension-example-docker
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    environment:
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: localhost
    links:
      - master
    ports:
      - 8081:8081

