name: Lint

on:
  workflow_call:

env:
  SCALAFMT_VERSION: 3.7.14

jobs:
  test:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install scalafmt directly
        run: |
          wget -O scalafmt https://github.com/scalameta/scalafmt/releases/download/v$SCALAFMT_VERSION/scalafmt-linux-glibc
          chmod +x scalafmt
          sudo mv scalafmt /usr/local/bin
          scalafmt -version

      - name: Lint - Scala
        run: scalafmt --test
        shell: bash
