name: Release

on:
  workflow_run:
    branches: "v*"
    workflows: ["CI"]
    types:
      - completed

permissions:
  contents: write

jobs:
  release:
    if: |
      github.event.workflow_run.event == 'push' &&
      github.event.workflow_run.conclusion == 'success' &&
      github.repository_owner == 'G-Research'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: "${{ github.event.workflow_run.head_branch }}"
          tag_name: ${{ github.event.workflow_run.head_branch }}
